import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import AosProvider from "@/provider/aos-provider";
import Header from "@/components/header";
import {cn} from "@/lib/utils";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={cn(inter.className, "relative bg-[url('/bg.png')] bg-contain bg-top bg-no-repeat")}>
        <AosProvider>
            <Header/>
            {children}
        </AosProvider>
        </body>
        </html>
    )
}
