export const personal_project = [
  {
    name: 'NextBlog',
    slug: 'next-blog',
    description: '基于 Next.js 的个人博客',
    link: 'https://next-blog.imyuanli.cn',
    poweredBy: 'next',
  },
  {
    name: 'ATools',
    slug: 'atools',
    description: '你最好的工具伙伴',
    link: 'https://atools.imyuanli.cn',
    poweredBy: 'umi',
  },
  {
    name: 'RMX',
    slug: 'rmx',
    description: 'RMX可以帮助开发人员快速制作项目的README.md',
    link: 'https://rmx.imyuanli.cn',
    poweredBy: 'umi',
  },
  {
    name: 'SlashEditor',
    slug: 'slash',
    description: '输入一个 / 就能开始你的富文本编辑旅程',
    link: 'https://slash.imyuanli.cn',
    poweredBy: 'next',
  },
  {
    name: 'FaceIt',
    slug: 'faceit',
    description: '简单几步制作独属于你自己的精美头像',
    link: 'https://faceit.imyuanli.cn',
    poweredBy: 'umi',
  },
  {
    name: 'Mini 起始页',
    slug: 'mini',
    description: '一个简洁的起始页',
    link: 'https://mini.imyuanli.cn',
    status: 'Upgrading',
    poweredBy: 'vue',
  },
  {
    name: 'BingAi',
    slug: 'bingai',
    description: '通过第三方链接 BingAi 打造自己的BingAi',
    link: 'https://bingai.imyuanli.cn',
    status: 'ARCHIVE',
    poweredBy: 'other',
  },
  {
    name: '小小简历',
    slug: 'xxcv',
    description: '简历编辑器',
    link: 'https://xxcv.imyuanli.cn',
    status: 'Upgrading',
    poweredBy: 'react',
  },
  {
    name: 'Projx',
    slug: 'projx',
    description: 'Projx-您的终极项目管理引擎',
    link: 'https://projx.imyuanli.cn',
    status: 'DEV',
    poweredBy: 'next',
  },
  {
    name: 'Hush',
    slug: 'hush',
    description: '一个更安全的文件分享平台',
    link: 'https://hush.imyuanli.cn',
    status: 'Upgrading',
    poweredBy: 'nuxt',
  },
  {
    name: '旧版个人网站',
    slug: 'old-imyuanli.cn',
    description: '旧版本的个人网站',
    link: 'https://old.imyuanli.cn',
    status: 'ARCHIVE',
    poweredBy: 'next',
  },
  {
    name: 'blog',
    slug: 'blog',
    description: '博客',
    link: 'https://blog.imyuanli.cn',
    status: 'FAILED',
    poweredBy: 'react',
  },
  {
    name: '快分享',
    slug: 'fastshare',
    description: '创建独属于你自己的分享社区',
    link: 'https://fastshare.imyuanli.cn',
    poweredBy: 'umi',
    status: 'FAILED',
  },
]
export const company_project = [
  {
    name: '简则 MBTI 官网',
    slug: 'jianze',
    description: '简则MBTI的官网页面,一个全栈项目',
    link: 'https://jzmbti.com/',
    poweredBy: 'fastapi',
  },
  {
    name: '简则 MBTI 个人版',
    slug: 'jianze',
    description: '简则MBTI，包含多种性格测试',
    link: 'https://jzmbti.com/pages/assessment/start/start',
    poweredBy: 'taro',
  },
  {
    name: '简则MBTI 企业版',
    slug: 'jianze',
    description: '专注于为企业提供人才测评服务',
    link: 'https://enterprise.jzmbti.com',
    poweredBy: 'umi',
  },
  {
    name: '16人格测试',
    slug: 'jianze',
    description: '简则MBTI副网址，用来进行 AB Testing 分析',
    link: 'https://enterprise.jzmbti.com',
    poweredBy: 'taro',
  },
  {
    name: '秒出 PPT (原简则 PPT)',
    slug: 'jianzeppt',
    description: 'AI 一键生成 ppt',
    link: 'https://10sppt.com/pptx/',
    poweredBy: 'umi',
  },
  {
    name: 'Synjq',
    description: '一款专注于异构数据库的同步软件',
    link: 'https://9bridges.cn/#',
    poweredBy: 'remix',
  },
  {
    name: 'FZS',
    description: '一款专注于异构数据库的同步软件',
    link: 'https://9bridges.cn/#',
    poweredBy: 'remix',
  },
]
